name = "hls-proxy-worker"           # Name of your Worker
main = "src/index.js"               # Entry file for your Worker
account_id = "f700a4562154ead08fcc94fed4e666de"  # Your Cloudflare account ID
workers_dev = true                   # Deploy to a workers.dev subdomain
compatibility_date = "2025-09-24"   # Keep this current

[build]
command = ""                         # Leave empty if no build step
